sudo: required
language: node_js
node_js:
  - "node"
# Yarn throws up unexpected key in travis lint
#cache:
#  - yarn
git:
  submodules: false
services:
  - docker
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - yarn install
install:
  - tsc -p .
  - docker-compose up
